### ISSUE TITLE
The home page seem to be broken

### ISSUE THREAD

**Issue by Josephu** [rkbalgi/isosim#50]
Thank you so much for your great ISOSIM app, I really appreciate the work.

Today I am just trying out the new build, and it seem `http://localhost:8080/iso/home` is not working anymore. Is that intended to remove the test request page? It is really useful for testing.

And if not, then it looks like the non-reactive app link is broken. When I click it, it says, 404 page not found ...
![Screen Shot 2020-04-22 at 3 43 03 pm](https://user-images.githubusercontent.com/1478562/79944906-0880f100-84b0-11ea-94e6-691f08dc9692.png)

Note also that the wiki for command line need to be updated, as you moved the folders into `test/testdata`.

https://github.com/rkbalgi/isosim/wiki/Start-standalone-ISO-server-from-command-line

**Comment by rkbalgi** [comment]
Hi Jim,Than kyou for using my application ! Yes, I have removed the older pages (at /iso/home), but the react pages should work. In your below image, try clicking on one of the spec names? And then when the messages show up, try clicking on one of the messages and you should be able to see the layout? Let me know what happens.   Sent from Mail for Windows 10 From: Jimmy WongSent: 22 April 2020 11:14To: rkbalgi/isosimCc: SubscribedSubject: [rkbalgi/isosim] The home page seem to be lost (#50) Hi. thank you so much for your great ISOSIM app, I really appreciate the work.Today I am just trying out the new build, and it seem http://localhost:8080/iso/home is not working anymore. Is that intended to remove the test request page? It is really useful for testing.And if not, then it looks like the non-reactive app link is broken...—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Josephu** [comment]
I see, that removes duplicate send message pages 👍 I was not aware you can click the specs, showing how useful your examples are ! Thanks.

**Comment by rkbalgi** [comment]
Closing these for now, please open if needed.
